### ISSUE TITLE
Unwetterkarte: Link falsch 404

### ISSUE THREAD

**Issue by twitnic** [veenmeyer/mod_eiko_unwetter#1]
Wenn man die Unwetterkarte nutzt, verlinkt diese im Fall von Sachsen auf den Parameter Sac.
https://www.dwd.de/DE/wetter/warnungen/Warnkarten/warnWetter_sac_node.html?bundesland=sac
Dies liefert aber einen 404 Fehler.

Ich weiß nicht ob es der richtige Link ist, aber sollte der das hier sein? http://www.dwd.de/DE/wetter/warnungen/warnkarten/warnWetter_sac_node.html?bundesland=sac

Sollte als an zu vielen großen Buchstaben in der URL liegen ...

Problem ist hier zu finden https://www.feuerwehr-falkenau.de

**Comment by veenmeyer** [comment]
Danke nochmal für den Hinweis ...
Fehler ist jetzt behoben.
https://github.com/veenmeyer/mod_eiko_unwetter/commit/ce9db492de03d2c006b11c02340c646307ca7439
